title: Travel booking APIs | Flight, Hotel, Car booking API by Allmyles
description: Travel APIs by Allmyles is the only Global Flight, Hotel, Car Rental booking API provides access to bookable travel content to build innovative web or native apps.
email: info@allmyles.com
url: "https://allmyles.com/"

exclude:
  - vendor
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
