title: Travel API by Allmyles
url: "http://allmyles.com/"
repository: balazsszilardtoth/allmyles.github.io

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - bin

sass:
  sass_dir: _sass
  style: compressed

# Ensure UTF-8 encoding
encoding: utf-8

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
